Repository acikkaynak/deprem-yardim-backend-go, pull requests merged in 2023-02, with the labels that each got.

#51 feat: issue-50 swagger eklendi
  README.md
  app/Application.go
  go.mod
  go.sum
  handler/create_event_handler.go
  handler/get_feed_areas.go
  handler/get_feed_by_id.go
  handler/healthcheck.go
  handler/register_swagger.go
  main.go
  swagger/docs.go
  swagger/swagger.json
  swagger/swagger.yaml
Labels: approved, kurala-uygun-pr

#63 reason field added on api response
  feeds/feed.go
  main.go
  repository/repository.go
Labels: kurala-uygun-pr

#71 Feed reason and channel params added
  feeds/feed.go
  handler/get_feed_areas.go
  repository/repository.go
Labels: kurala-uygun-pr

#77 feat: consumer integration
  README.md
  broker/kafka_consumer.go
  cmd/api/main.go
  cmd/consumer/main.go
  docker-compose.yml
  feeds/feed.go
  handler/create_event_handler.go
  repository/repository.go
  swagger/docs.go
  swagger/swagger.json
  swagger/swagger.yaml
Labels: approved

#80 add intent resolve consumer
  broker/kafka_producer.go
  cmd/consumer/main.go
  go-prod.env
  prometheus.yml
  repository/repository.go
Labels: approved

#82 Event request fix and swagger definition edited
  README.md
  cmd/api/main.go
  handler/create_event_handler.go
  handler/get_feed_areas.go
  swagger/docs.go
  swagger/swagger.json
  swagger/swagger.yaml
Labels: kurala-uygun-pr

#112 Update feeds location endpoint
  cmd/api/main.go
  feeds/feed.go
  handler/update_feed_location_handler.go
  middleware/auth/auth.go
  repository/repository.go
  swagger/docs.go
  swagger/swagger.json
  swagger/swagger.yaml
Labels: approved

#142 add duplication api request & refactor
  cmd/consumer/main.go
  consumer/adress_resolved_handler.go
  consumer/consumer.go
  consumer/intents_resolver.go
  consumer/needs_resolver.go
  go-prod.env
Labels: approved
